language: node_js

sudo: required

node_js:
  - "10"

branches:
  only:
    - master

install:
  - npm install

script:
  - npm test
  - npm run lint:md
  - npm run lint:text
   
notifications:
   on_success: change
   on_failure: always